[project]
name = "frames"
version = "0.1.0"
description = "Implementation of various frame algorithms."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.3",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "plotly>=6.1.0",
]
